export interface SeedLead {
  company: string;
  type: 'B2B' | 'Residential';
  location: string;
  industry: string;
  employees: number | null;
  contactName: string;
  email: string;
  phone: string;
  source: string;
  notes: string;
}

// Shuffled list — mix of qualifying and disqualifying leads
export const SEED_LEADS: SeedLead[] = [
  {
    company: 'Smarten Logistics AS',
    type: 'B2B',
    location: 'Tallinn (Rae)',
    industry: 'Warehousing / Logistics',
    employees: 150,
    contactName: 'Andrus Koppel',
    email: 'andrus.koppel@smarten.ee',
    phone: '+372 5345 6789',
    source: 'Trade show (GreenTech Estonia)',
    notes: 'Largest Estonian-owned 3PL provider. Multiple large warehouse roofs. Looking into ESG reporting & energy cost reduction.',
  },
  {
    company: 'Forwex Estonia OÜ',
    type: 'B2B',
    location: 'Tallinn (Pirita)',
    industry: 'Logistics / Freight Forwarding',
    employees: 20,
    contactName: 'Igor Petrov',
    email: 'igor.petrov@forwex.ee',
    phone: '+372 5123 4568',
    source: 'LinkedIn connection request',
    notes: 'Freight forwarding company — office-only operation, no warehouses owned. Rents 200m² office space in business park.',
  },
  {
    company: 'Hedon Spa & Hotel',
    type: 'B2B',
    location: 'Pärnu',
    industry: 'Hospitality / Hotel',
    employees: 80,
    contactName: 'Margus Linna',
    email: 'margus.linna@hedonspa.com',
    phone: '+372 5123 4567',
    source: 'LinkedIn outbound',
    notes: 'Large spa hotel with flat rooftop. High energy costs from pool heating & spa operations. Interested in sustainability branding.',
  },
  {
    company: 'Aleksei Volkov',
    type: 'Residential',
    location: 'Lasnamäe, Tallinn',
    industry: 'Homeowner (apartment)',
    employees: null,
    contactName: 'Aleksei Volkov',
    email: 'aleksei.volkov@mail.ee',
    phone: '+372 5234 5679',
    source: 'Google Ads',
    notes: 'Lives in 9th floor apartment in Soviet-era panel building. Interested in solar but has no roof access or decision authority.',
  },
  {
    company: 'Väike Päike (Laagri daycare)',
    type: 'B2B',
    location: 'Laagri, Harjumaa',
    industry: 'Education / Childcare',
    employees: 35,
    contactName: 'Piret Uus',
    email: 'piret.uus@lasteklubi.ee',
    phone: '+372 5456 7890',
    source: 'Referral from existing customer',
    notes: 'Private daycare chain with multiple locations. Laagri building has good south-facing roof. Interested in green marketing to parents.',
  },
  {
    company: 'Werner Cafe',
    type: 'B2B',
    location: 'Tartu',
    industry: 'Café / Restaurant',
    employees: 10,
    contactName: 'Kadri Laas',
    email: 'kadri@wernercafe.ee',
    phone: '+372 5345 6780',
    source: 'Walk-in at trade show',
    notes: 'Historic café on Tartu Town Hall Square. Operates in rented ground-floor space of a heritage-protected building.',
  },
  {
    company: 'Saaremaa Piimatööstus (MO Saaremaa)',
    type: 'B2B',
    location: 'Kuressaare, Saaremaa',
    industry: 'Food Manufacturing / Dairy',
    employees: 120,
    contactName: 'Tõnis Valk',
    email: 'tonis.valk@mosaaremaa.ee',
    phone: '+372 5567 8901',
    source: 'Cold email outreach',
    notes: 'Largest organic dairy producer in Estonia. Modern production facility with large roof. Already has sustainability certifications (FSSC 22000, ISO 45001).',
  },
  {
    company: 'Bolt Technology OÜ',
    type: 'B2B',
    location: 'Tallinn',
    industry: 'Technology / Ride-hailing',
    employees: 4000,
    contactName: 'General inquiry',
    email: 'sustainability@bolt.eu',
    phone: '+372 6 123 456',
    source: 'Website form',
    notes: 'Major tech company inquiring about solar for their HQ. Enterprise-level procurement process, 12+ month decision cycle.',
  },
  {
    company: 'Jaan & Maria Tammsaar',
    type: 'Residential',
    location: 'Nõmme, Tallinn',
    industry: 'Homeowner',
    employees: null,
    contactName: 'Jaan Tammsaar',
    email: 'jaan.tammsaar@gmail.com',
    phone: '+372 5678 9012',
    source: 'Google Ads',
    notes: 'Couple in their 40s, renovated 1930s wooden house. South-facing roof, no shading. Interested in reducing €180/month electricity bill.',
  },
  {
    company: 'Tallinn International Kindergarten',
    type: 'B2B',
    location: 'Tallinn (Kesklinn)',
    industry: 'Education / Childcare',
    employees: 15,
    contactName: 'Sarah Mitchell',
    email: 'sarah.mitchell@kindergarten.ee',
    phone: '+372 5567 8902',
    source: 'Email inquiry',
    notes: 'Private kindergarten in rented residential building in central Tallinn. Building owned by separate property company.',
  },
  {
    company: 'Kalamaja Pagarikoda',
    type: 'B2B',
    location: 'Tallinn (Kalamaja)',
    industry: 'Bakery / Food Service',
    employees: 12,
    contactName: 'Triin Kallas',
    email: 'triin@kalamajapagarikoda.ee',
    phone: '+372 5890 1234',
    source: 'Referral',
    notes: 'Artisan bakery with own building. Ovens run 14hrs/day — very high electricity costs. Owner is personally passionate about sustainability.',
  },
  {
    company: 'OÜ DigitalNomad Consulting',
    type: 'B2B',
    location: 'Tallinn (remote)',
    industry: 'IT Consulting',
    employees: 3,
    contactName: 'Martin Aas',
    email: 'martin@digitalnomad.ee',
    phone: '+372 5678 9013',
    source: 'LinkedIn',
    notes: '3-person IT consulting firm. Works remotely from co-working spaces. No physical office or property. Curious about solar for personal home.',
  },
  {
    company: 'Villa Ammende',
    type: 'B2B',
    location: 'Pärnu',
    industry: 'Hospitality / Restaurant & Hotel',
    employees: 25,
    contactName: 'Kätlin Org',
    email: 'katlin@ammende.ee',
    phone: '+372 5234 5678',
    source: 'Website form',
    notes: 'Boutique luxury hotel in Art Nouveau villa. Looking to reduce operating costs and appeal to eco-conscious tourists.',
  },
  {
    company: 'Katrin & Siim Lepik',
    type: 'Residential',
    location: 'Viimsi, Harjumaa',
    industry: 'Homeowner',
    employees: null,
    contactName: 'Katrin Lepik',
    email: 'katrin.lepik@gmail.com',
    phone: '+372 5901 2346',
    source: 'Referral from neighbor',
    notes: 'Young family, just built new house in Viimsi. Roof is north-facing with heavy tree cover. Already spent full renovation budget.',
  },
  {
    company: 'Tartu Hotel (Hotel Pärnu group)',
    type: 'B2B',
    location: 'Tartu',
    industry: 'Hospitality / Hotel',
    employees: 30,
    contactName: 'Liina Mets',
    email: 'liina.mets@tartuhotel.ee',
    phone: '+372 5789 0123',
    source: 'Website organic',
    notes: 'Mid-range city-center hotel. Looking at energy efficiency upgrades as part of planned renovation in 2027.',
  },
  {
    company: 'Peeter Kõiv',
    type: 'Residential',
    location: 'Narva',
    industry: 'Homeowner',
    employees: null,
    contactName: 'Peeter Kõiv',
    email: 'peeter.koiv@hot.ee',
    phone: '+372 5456 7891',
    source: 'Facebook ad',
    notes: 'Homeowner in Narva (eastern Estonia). Owns detached house with good roof. Interested but NordLight doesn\'t operate in Ida-Virumaa.',
  },
  {
    company: 'Cruffin Bakehouse',
    type: 'B2B',
    location: 'Tartu',
    industry: 'Café / Bakery',
    employees: 6,
    contactName: 'Sander Kivimägi',
    email: 'sander@cruffin.ee',
    phone: '+372 5901 2345',
    source: 'Instagram DM',
    notes: 'Trendy croissanterie in rented space in Tartu city center. Interested in \'going green\' but doesn\'t own the property.',
  },
  {
    company: 'Laki Logistics (Tartu terminal)',
    type: 'B2B',
    location: 'Tartu',
    industry: 'Logistics / Distribution',
    employees: 45,
    contactName: 'Raimo Järv',
    email: 'raimo.jarv@laki.ee',
    phone: '+372 5890 1235',
    source: 'Trade show',
    notes: 'Distribution terminal in Tartu. Large flat-roof warehouse. However, building is leased from Mainor Ülemiste — not owned.',
  },
  {
    company: 'Hiiumaa Köök ja Pagar OÜ',
    type: 'B2B',
    location: 'Kärdla, Hiiumaa',
    industry: 'Food Production',
    employees: 8,
    contactName: 'Ülle Rand',
    email: 'ulle@hiiumaapagarid.ee',
    phone: '+372 5012 3456',
    source: 'Cold email',
    notes: 'Small food producer on Hiiumaa island. Owns building. Interested in energy independence due to unreliable grid on island.',
  },
  {
    company: 'Padu Hotell',
    type: 'B2B',
    location: 'Kärdla, Hiiumaa',
    industry: 'Hospitality / Guesthouse',
    employees: 4,
    contactName: 'Maris Saar',
    email: 'maris@paduhotell.ee',
    phone: '+372 5789 0124',
    source: 'Website form',
    notes: 'Small seasonal guesthouse on Hiiumaa. Open only June–August. Very small electricity usage. Owns property but tiny building.',
  },
];
